sonar.projectKey=steven-patterson17_Vr_Training_Application
sonar.organization=steven-patterson17

# Tell Sonar where your code is
sonar.sources=Assets

# Only analyze C# files
sonar.inclusions=**/*.cs

# Exclude Unity junk folders
sonar.exclusions=Library/**,Logs/**,Temp/**,obj/**,bin/**, Assets/Plugins/Android/FirebaseApp.androidlib/**/*

# (Optional but helpful)
sonar.sourceEncoding=UTF-8
