sonar.projectKey=Caleb-Kendig_test
sonar.organization=caleb-kendig

# Tell Sonar where your code is
sonar.sources=Assets

# Only analyze C# files
sonar.inclusions=**/*.cs

# Exclude Unity junk folders
sonar.exclusions=Library/**,Logs/**,Temp/**,obj/**,bin/**

# (Optional but helpful)
sonar.sourceEncoding=UTF-8
